# Generated by Django 3.1 on 2020-08-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_in_room',
            name='reservation',
        ),
    ]
