# Generated by Django 3.1 on 2020-08-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_student_in_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_in_room',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hostel.reservation'),
        ),
    ]
